trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '*'

variables:
  - name: 'vmIpAddress'
    value: '74.234.112.155'
  - name: 'sshUser'
    value: 'razumovsky_r'

stages:
  - stage: 'SSH_task_Windows'
    displayName: 'SSH Task Windows'
    jobs:
      - job: 'Build'
        displayName: 'SSH Task Windows'
        pool:
          vmImage: 'windows-latest'
        
        steps:
          - task: SSH@0
            inputs:
              sshEndpoint: 'WindowsSSHConnection'
              runOptions: 'commands'
              commands: |
                powershell Get-Content C:\ProgramData\ssh\administrators_authorized_keys

          - task: DownloadSecureFile@1
            name: sshKey
            displayName: 'Download SSH key'
            inputs:
              secureFile: 'id_rsa_windows'
              
          - task: PowerShell@2
            displayName: 'Copy SSH Key'
            inputs:
              targetType: 'inline'
              script: |
                Copy-Item $(sshKey.secureFilePath) -Destination "~/.ssh/id_rsa_windows"
          
          # Windows agent looks for ssh config in folders:
          # debug3: Failed to open file:C:/Users/VssAdministrator/.ssh/config error:2
          # debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
          - task: PowerShell@2
            displayName: 'Add SSH Config'
            inputs:
              targetType: 'inline'
              script: |
                Copy-Item ssh_config -Destination "C:/Users/VssAdministrator/.ssh/config"

          - script: ssh staging -vvv "powershell Get-Content C:\ProgramData\ssh\administrators_authorized_keys"
            displayName: 'Test SSH Config'

          - script: ssh -v $(sshUser)@$(vmIpAddress) "powershell Get-Content C:\ProgramData\ssh\administrators_authorized_keys"
            displayName: 'Test SSH Connection'

          - script: |
              chmod 600 $(sshKey.secureFilePath)
              scp -r -i $(sshKey.secureFilePath) ansible_hotel360.yml \
                $(sshUser)@$(vmIpAddress):C:/Users/razumovsky_r/Desktop/ansible_hotel360_pipeline_copy.yml
            displayName: 'Copy Ansible Playbook to VM'