trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '*'

stages:
  - stage: 'SSH_task'
    displayName: 'SSH Task'
    jobs:
      - job: 'Build'
        displayName: 'SSH Task'
        pool:
          vmImage: 'ubuntu-latest'
        
        steps:
          - task: SSH@0
            inputs:
              sshEndpoint: 'SSHConnection'
              runOptions: 'commands'
              commands: |
                cat ~/.ssh/authorized_keys


          - task: ms-vscs-rm.vss-services-ansible.ansible-task.Ansible@0
            displayName: 'Run playbook'
            inputs:
              ansibleInterface: remoteMachine
              connectionOverSsh: SSHConnection
              playbookRootRemoteMachine: '$(System.DefaultWorkingDirectory)'
              playbookPathLinkedArtifactOnRemoteMachine: ansible_hotel360.yml
              inventoriesRemoteMachine: hostList
              inventoryHostListRemoteMachine: 20.223.160.235