trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '*'

variables:
  - name: 'vmIpAddress'
    value: '20.223.160.235'
  - name: 'sshUser'
    value: 'razumovsky_r'

stages:
  - stage: 'SSH_task'
    displayName: 'SSH Task'
    jobs:
      - job: 'Build'
        displayName: 'SSH Task'
        pool:
          vmImage: 'ubuntu-latest'
        
        steps:
          - task: SSH@0
            inputs:
              sshEndpoint: 'SSHConnection'
              runOptions: 'commands'
              commands: |
                cat ~/.ssh/authorized_keys

          - task: DownloadSecureFile@1
            name: sshKey
            displayName: 'Download SSH key'
            inputs:
              secureFile: 'id_rsa'

          - script: |
              echo "Installing $(sshKey.secureFilePath) to SSH config"
              mkdir -p ~/.ssh/
              cp $(sshKey.secureFilePath) ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              cat >>~/.ssh/config <<END
              Host staging
                HostName $(vmIpAddress)
                User $(sshUser)
                IdentityFile ~/.ssh/id_rsa
                StrictHostKeyChecking no
              END
            displayName: 'Add SSH Config'

          - script: cat ~/.ssh/config
            displayName: 'Print SSH Config'

          - script: ssh staging -v "hostname"
            displayName: 'Test SSH Config'

          - script: ssh -v $(sshUser)@$(vmIpAddress) "hostname"
            displayName: 'Test SSH Connection'

          - script: |
              chmod 600 $(sshKey.secureFilePath)
              scp -r -i $(sshKey.secureFilePath) ansible_hotel360.yml $(sshUser)@$(vmIpAddress):/home/$(sshUser)/ansible_playbooks/ansible_hotel360_azdo_copy.yml
            displayName: 'Copy Ansible Playbook to VM'
          
          
          
          # - task: ms-vscs-rm.vss-services-ansible.ansible-task.Ansible@0
          #   displayName: 'Run playbook'
          #   inputs:
          #     ansibleInterface: remoteMachine
          #     connectionOverSsh: SSHConnection
          #     playbookRootRemoteMachine: '$(System.DefaultWorkingDirectory)'
          #     playbookPathLinkedArtifactOnRemoteMachine: ansible_hotel360.yml
          #     inventoriesRemoteMachine: hostList
          #     inventoryHostListRemoteMachine: 20.223.160.235