name: SSH Windows Agent To Ubuntu

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

env:
  VM_IP_ADDRESS: sshubuntu.devtest.team
  SSH_USER: razumovsky_r

jobs:
  gha-ssh-windows-agent-to-ubuntu:
    name: SSH Windows Agent To Ubuntu
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Copy SSH Key'
        shell: pwsh
        run: |
          New-Item -Path "~/.ssh/id_rsa" -ItemType "file" -Value $env:SSH_KEY -Force
          dir ~/.ssh
        env:
          SSH_KEY: ${{ secrets.UBUNTU_SSH_KEY }}
          
      - name: 'Configure SSH'
        shell: pwsh
        run: |
          Copy-Item ssh_config -Destination "C:/Users/runneradmin/.ssh/config"

      - name: 'Print SSH Config'
        run: Get-Content "C:/Users/runneradmin/.ssh/config"
        shell: pwsh

      - name: Test SSH Config
        run: ssh ubuntu -vvv "cat ~/.ssh/authorized_keys"
        shell: pwsh

      - name: 'Test SSH Connection'
        run: | 
          ssh -i "~/.ssh/id_rsa" -v ${{ env.SSH_USER }}@${{ env.VM_IP_ADDRESS }} `
            "cat ~/.ssh/authorized_keys"
        shell: pwsh

      - name: 'Copy Ansible Playbook to VM'
        run: |
          $config="C:/Users/runneradmin/.ssh/config"
          $key="~/.ssh/id_rsa"
          $dest="~/ansible_playbooks/ansible_hotel360_ssh_windows3_agent_copy.yml"
          scp -F $config -i $key ansible_hotel360.yml ${{ env.SSH_USER }}@${{ env.VM_IP_ADDRESS }}:$dest
          ssh ubuntu -v "cat $dest"
        shell: pwsh