name: SSH Windows Agent To Windows

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

env:
  VM_IP_ADDRESS: ssh-windows.razumovsky.me
  SSH_USER: razumovsky_r

jobs:
  gha-ssh-windows-agent-to-windows:
    name: SSH Windows Agent To Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Copy SSH Key'
        shell: pwsh
        run: |
          New-Item -Path "~/.ssh/id_rsa" -ItemType "file" -Value $env:SSH_KEY -Force
          dir ~/.ssh
        env:
          SSH_KEY: ${{ secrets.UBUNTU_SSH_KEY }}

      - name: 'Configure SSH'
        shell: pwsh
        run: |
          Copy-Item ssh_config -Destination "C:/Users/runneradmin/.ssh/config"

      - name: 'Print SSH Config'
        run: Get-Content "C:/Users/runneradmin/.ssh/config"
        shell: pwsh

      - name: 'Test SSH Config'
        run: ssh windows -vvv "powershell Get-Content C:\ProgramData\ssh\administrators_authorized_keys"
        shell: pwsh

      - name: 'Test SSH Connection'
        run: |
          ssh -i "~/.ssh/id_rsa" -v ${{ env.SSH_USER }}@${{ env.VM_IP_ADDRESS }} `
            "powershell Get-Content C:\ProgramData\ssh\administrators_authorized_keys"
        shell: pwsh
