#trigger:
#  batch: true
#  branches:
#    include:
#      - master
#  paths:
#    include:
#      - '*'

trigger: none

variables:
  - name: 'vmIpAddress'
    value: '20.238.72.235'
  - name: 'sshUser'
    value: 'razumovsky_r'
  - group: 'ssh-settings'

stages:
  - stage: 'SSH_Ubuntu_Agent_To_Ubuntu'
    displayName: 'SSH Ubuntu Agent To Ubuntu'
    jobs:
      - job: 'Build'
        displayName: 'SSH Ubuntu Agent To Ubuntu'
        pool:
          vmImage: 'ubuntu-latest'
        
        steps:
          - task: InstallSSHKey@0
            displayName: 'Install an SSH key'
            inputs:
              knownHostsEntry: '$(known_hosts)'   # known_hosts file contents from local machine after 'ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts'
              sshPublicKey: '$(id_rsa.pub)'       # public key plain text from library
              sshKeySecureFile: 'id_rsa'          # private key from secure files

          - script: ssh -v $(sshUser)@$(vmIpAddress) "hostname"
            displayName: 'Test SSH Connection'