#trigger:
#  batch: true
#  branches:
#    include:
#      - master
#  paths:
#    include:
#      - '*'

trigger: none

variables:
  - name: 'vmIpAddress'
    value: '74.234.112.155'
  - name: 'sshUser'
    value: 'razumovsky_r'

stages:
  - stage: 'SSH_Windows_Agent_To_Windows'
    displayName: 'SSH Windows Agent To Windows'
    jobs:
      - job: 'Build'
        displayName: 'SSH Windows Agent To Windows'
        pool:
          vmImage: 'windows-latest'
        
        steps:
          - task: SSH@0
            inputs:
              sshEndpoint: 'WindowsSSHConnection'
              runOptions: 'commands'
              commands: |
                powershell Get-Content C:\ProgramData\ssh\administrators_authorized_keys

          - task: DownloadSecureFile@1
            name: sshKey
            displayName: 'Download SSH key'
            inputs:
              secureFile: 'id_rsa_windows'

          - task: PowerShell@2
            displayName: 'Copy SSH Key'
            inputs:
              targetType: 'inline'
              script: |
                New-Item -Path "~/.ssh/id_rsa_windows" -ItemType "file" -Force
                Copy-Item $(sshKey.secureFilePath) -Destination "~/.ssh/id_rsa_windows"
          
          # Windows agent looks for ssh config in folders:
          # debug3: Failed to open file:C:/Users/VssAdministrator/.ssh/config error:2
          # debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
          - task: PowerShell@2
            displayName: 'Add SSH Config'
            inputs:
              targetType: 'inline'
              script: |
                Copy-Item ssh_config -Destination "C:/Users/VssAdministrator/.ssh/config"
                Get-Content "C:/Users/VssAdministrator/.ssh/config"

          - script: ssh windows -vvv "powershell Get-Content C:\ProgramData\ssh\administrators_authorized_keys"
            displayName: 'Test SSH Config'

          - script: |
              ssh -i "~/.ssh/id_rsa_windows" -v $(sshUser)@$(vmIpAddress) "powershell Get-Content C:\ProgramData\ssh\administrators_authorized_keys"
            displayName: 'Test SSH Connection'

          - task: PowerShell@2
            displayName: 'Copy Ansible Playbook to VM'
            inputs:
              targetType: 'inline'
              script: |
                $config="C:/Users/VssAdministrator/.ssh/config"
                $key="~/.ssh/id_rsa_windows"
                scp -F $config -i $key ansible_hotel360.yml $(sshUser)@$(vmIpAddress):C:/Users/razumovsky_r/Desktop/ansible_hotel360_ssh_windows_agent_copy.yml
                ssh windows -v "powershell Get-Content C:/Users/razumovsky_r/Desktop/ansible_hotel360_ssh_windows_agent_copy.yml"