trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '*'

#trigger: none

variables:
  - name: 'VM_DNS'
    value: 'ssh-windows.razumovsky.me'
  - name: 'VM_USER'
    value: 'razumovsky_r'
  - name: 'System.Debug'
    value: 'true'

stages:
  - stage: 'SSH_Windows_Agent_To_Windows'
    displayName: 'SSH Windows Agent To Windows'
    jobs:
      - job: 'Build'
        displayName: 'SSH Windows Agent To Windows'
        pool:
          vmImage: 'windows-latest'

        steps:
          - task: SSH@0
            inputs:
              sshEndpoint: 'WindowsSSHConnection'
              runOptions: 'commands'
              commands: |
                powershell Get-Content C:\ProgramData\ssh\administrators_authorized_keys

          - task: DownloadSecureFile@1
            name: sshKey
            displayName: 'Download SSH key'
            inputs:
              secureFile: 'id_rsa'

          - task: PowerShell@2
            displayName: 'Copy SSH Key'
            inputs:
              targetType: 'inline'
              script: |
                New-Item -Path "~/.ssh/id_rsa" -ItemType "file" -Force
                Copy-Item $(sshKey.secureFilePath) -Destination "~/.ssh/id_rsa"

          # Windows agent looks for ssh config in folders:
          # debug3: Failed to open file:C:/Users/VssAdministrator/.ssh/config error:2
          # debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
          - task: PowerShell@2
            displayName: 'Add SSH Config'
            inputs:
              targetType: 'inline'
              script: |
                Copy-Item ssh_config -Destination "C:/Users/VssAdministrator/.ssh/config"
                Get-Content "C:/Users/VssAdministrator/.ssh/config"

          - script: ssh windows -vvv "powershell Get-Content C:\ProgramData\ssh\administrators_authorized_keys"
            displayName: 'Test SSH Config'

          - script: |
              ssh -i "~/.ssh/id_rsa" -v $(VM_USER)@$(VM_DNS) "powershell Get-Content C:\ProgramData\ssh\administrators_authorized_keys"
            displayName: 'Test SSH Connection'
