#trigger:
#  batch: true
#  branches:
#    include:
#      - master
#  paths:
#    include:
#      - '*'

trigger: none

variables:
  - name: 'VM_DNS'
    value: 'sshubuntu.devtest.team'
  - name: 'VM_USER'
    value: 'razumovsky_r'

stages:
  - stage: 'SSH_Ubuntu_Agent_To_Ubuntu'
    displayName: 'SSH Ubuntu Agent To Ubuntu'
    jobs:
      - job: 'Build'
        displayName: 'SSH Ubuntu Agent To Ubuntu'
        pool:
          vmImage: 'ubuntu-latest'
        
        steps:
          - task: SSH@0
            inputs:
              sshEndpoint: 'SSHConnection'
              runOptions: 'commands'
              commands: |
                cat ~/.ssh/authorized_keys

          - task: DownloadSecureFile@1
            name: sshKey
            displayName: 'Download SSH key'
            inputs:
              secureFile: 'id_rsa'

          - script: |
              echo "Installing $(sshKey.secureFilePath) to SSH config"
              mkdir -p ~/.ssh/
              cp $(sshKey.secureFilePath) ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              cat >>~/.ssh/config <<END
              Host staging
                HostName $(VM_DNS)
                User $(VM_USER)
                IdentityFile ~/.ssh/id_rsa
                StrictHostKeyChecking no
              END
            displayName: 'Add SSH Config'

          - script: cat ~/.ssh/config
            displayName: 'Print SSH Config'

          - script: ssh staging -v "hostname"
            displayName: 'Test SSH Config'

          - script: ssh -v $(VM_USER)@$(VM_DNS) "hostname"
            displayName: 'Test SSH Connection'

          - script: |
              chmod 600 $(sshKey.secureFilePath)
              scp -r -i $(sshKey.secureFilePath) ansible_hotel360.yml \
                $(VM_USER)@$(VM_DNS):/home/$(VM_USER)/ansible_playbooks/ansible_hotel360_azdo_copy.yml
            displayName: 'Copy Ansible Playbook to VM'