#trigger:
#  batch: true
#  branches:
#    include:
#      - master
#  paths:
#    include:
#      - '*'

trigger: none

variables:
  - name: 'VM_DNS'
    value: 'ssh-windows.razumovsky.me'
  - name: 'VM_USER'
    value: 'razumovsky_r'
  - name: 'System.Debug'
    value: 'true'

stages:
  - stage: 'SSH_Ubuntu_Agent_To_Windows'
    displayName: 'SSH Ubuntu Agent To Windows'
    jobs:
      - job: 'Build'
        displayName: 'SSH Ubuntu Agent To Windows'
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - task: SSH@0
            inputs:
              sshEndpoint: 'WindowsSSHConnection'
              runOptions: 'commands'
              commands: |
                powershell Get-Content C:\ProgramData\ssh\administrators_authorized_keys

          - task: DownloadSecureFile@1
            name: sshKey
            displayName: 'Download SSH key'
            inputs:
              secureFile: 'id_rsa'

          - script: |
              echo "Installing $(sshKey.secureFilePath) to SSH config"
              mkdir -p ~/.ssh/
              cp $(sshKey.secureFilePath) ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              cat >>~/.ssh/config <<END
              Host staging
                HostName $(VM_DNS)
                User $(VM_USER)
                IdentityFile ~/.ssh/id_rsa
                StrictHostKeyChecking no
              END
            displayName: 'Add SSH Config'

          - script: cat ~/.ssh/config
            displayName: 'Print SSH Config'

          - script: ssh staging -v "powershell Get-Content C:\ProgramData\ssh\administrators_authorized_keys"
            displayName: 'Test SSH Config'

          - script: ssh -v $(VM_USER)@$(VM_DNS) "powershell Get-Content C:\ProgramData\ssh\administrators_authorized_keys"
            displayName: 'Test SSH Connection'
